/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.MayBayBLL;
import DTO.KhachHangDTO;
import DTO.KhachHangSearchDTO;
import DTO.MayBayDTO;
import DTO.MayBaySearchDTO;
import Util.DateJcalendarUtil;
import Util.DateUtil;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.*;

/**
 * @author User
 */
public class MayBay_Panel extends javax.swing.JPanel {
    private MayBayBLL mayBayBLL = new MayBayBLL();
    private DefaultTableModel tblModel = new DefaultTableModel();
    private Map<String, String> cbxTrangThaiMap = new HashMap<>();
    private boolean checkSelectedRow;

    public MayBay_Panel() {
        initComponents();
        initCbxTrangThai();
        noChangeDataTable();
        initTable();
        fillTable();
    }

    private void initTable() {
        String[] colums = new String[]{"Mã máy bay", "Tên máy bay", "Số ghế thương gia",
                "Số ghế phổ thông", "Trạng thái"};
        tblModel.setColumnIdentifiers(colums);
        tableMayBay.setModel(tblModel);
    }

    private void fillTable() {
        tblModel.setRowCount(0);

        MayBaySearchDTO mayBaySearchDTO = initMayBaySearchDTO();

        for (MayBayDTO mayBayDTO : mayBayBLL.search(mayBaySearchDTO)) {
            tblModel.addRow(new Object[]{mayBayDTO.getId(), mayBayDTO.getTen(),
                    mayBayDTO.getSoGheH1(), mayBayDTO.getSoGheH2(),
                    mayBayDTO.isStatus() ? "Khả dụng" : "Không khả dụng"});
        }
        tblModel.fireTableDataChanged();
    }

    private void initCbxTrangThai() {
        String[] descriptions = {"Tất cả", "Khả dụng", "Không khả dụng"};
        String[] values = {"", "true", "false"};
        DefaultComboBoxModel<String> cbxModel = new DefaultComboBoxModel<>(descriptions);
        for (int i = 0; i < descriptions.length; i++) {
            cbxTrangThaiMap.put(descriptions[i], values[i]);
        }
        status.setModel(cbxModel);
    }

    private MayBaySearchDTO initMayBaySearchDTO() {
        MayBaySearchDTO mayBaySearchDTO = new MayBaySearchDTO();
        mayBaySearchDTO.setTenMaybay(name.getText());
        mayBaySearchDTO.setSoGheThuongGiaTu(soGheThuongGiaTu.getText());
        mayBaySearchDTO.setSoGheThuongGiaDen(soGheThuongGiaDen.getText());
        mayBaySearchDTO.setSoGhePhoThongTu(soGhePhoThongTu.getText());
        mayBaySearchDTO.setSoGhePhoThongDen(soGhePhoThongDen.getText());
        mayBaySearchDTO.setTrangThai(cbxTrangThaiMap.get(status.getSelectedItem()));
        return mayBaySearchDTO;
    }

    private void refreshInputSearch() {
        name.setText("");
        soGheThuongGiaTu.setText("");
        soGheThuongGiaDen.setText("");
        soGhePhoThongTu.setText("");
        soGhePhoThongDen.setText("");
        status.setSelectedIndex(0);
    }

    public void loadDataTable() {
        fillTable();
    }

    private void noChangeDataTable() {
        tblModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Make all cells non-editable
                return false;
            }
        };
        tableMayBay.setModel(tblModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        soGhePhoThongDen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JScrollPane = new javax.swing.JScrollPane();
        tableMayBay = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        soGheThuongGiaTu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        soGheThuongGiaDen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        soGhePhoThongTu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        btnRefresh = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        idMayBay = new javax.swing.JTextField();
        btnDetail = new javax.swing.JButton();
        xuatExecel = new javax.swing.JButton();
        nhapExcel = new javax.swing.JButton();

        soGhePhoThongDen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        soGhePhoThongDen.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên:");

//        JScrollPane.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                JScrollPaneMouseClicked(evt);
//            }
//        });

        tableMayBay.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null}
                },
                new String[]{
                        "Mã máy bay", "Tên máy bay", "Tình trạng"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                    false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tableMayBay.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableMayBay.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableMayBay.getTableHeader().setReorderingAllowed(false);
        tableMayBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMayBayMouseClicked(evt);
            }
        });
        JScrollPane.setViewportView(tableMayBay);
        if (tableMayBay.getColumnModel().getColumnCount() > 0) {
            tableMayBay.getColumnModel().getColumn(0).setResizable(false);
            tableMayBay.getColumnModel().getColumn(1).setResizable(false);
            tableMayBay.getColumnModel().getColumn(2).setResizable(false);
        }

        btnSearch.setBackground(new java.awt.Color(0, 153, 255));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText(" Danh sách máy bay");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Tìm kiếm máy bay");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Số ghế thương gia đến:");

        soGheThuongGiaTu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        soGheThuongGiaTu.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Số ghế phổ thông từ:");

        soGheThuongGiaDen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        soGheThuongGiaDen.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Số ghế thương gia từ:");

        name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Trạng thái:");

        soGhePhoThongTu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        soGhePhoThongTu.setBorder(null);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Số ghế phổ thông đến:");

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(0, 153, 255));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Đặt lại");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(0, 153, 255));
        btnCreate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Thêm máy bay");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(0, 153, 255));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Chỉnh sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 153, 255));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        idMayBay.setVisible(false);
        idMayBay.setEditable(false);
        idMayBay.setText("jTextField1");
        idMayBay.setEnabled(false);

        btnDetail.setBackground(new java.awt.Color(0, 153, 255));
        btnDetail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDetail.setForeground(new java.awt.Color(255, 255, 255));
        btnDetail.setText("Xem chi tiết");
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });

        xuatExecel.setBackground(new java.awt.Color(0, 153, 255));
        xuatExecel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        xuatExecel.setForeground(new java.awt.Color(255, 255, 255));
        xuatExecel.setText("Xuất excel");
        xuatExecel.setBorder(null);
        xuatExecel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xuatExecelActionPerformed(evt);
            }
        });

        nhapExcel.setBackground(new java.awt.Color(0, 153, 255));
        nhapExcel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nhapExcel.setForeground(new java.awt.Color(255, 255, 255));
        nhapExcel.setText("Nhập excel");
        nhapExcel.setBorder(null);
        nhapExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JScrollPane)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(soGhePhoThongTu, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(idMayBay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(30, 30, 30)
                                                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(31, 31, 31)
                                                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(27, 27, 27)
                                                                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(soGhePhoThongDen)
                                                                        .addComponent(soGheThuongGiaTu, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(138, 138, 138)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(btnSearch))
                                                                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(soGheThuongGiaDen, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(nhapExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(xuatExecel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addGap(57, 57, 57)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(xuatExecel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(nhapExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(soGheThuongGiaTu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(soGheThuongGiaDen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(soGhePhoThongTu, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                        .addComponent(soGhePhoThongDen)
                                        .addComponent(status))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(idMayBay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        MayBaySearchDTO mayBaySearchDTO = initMayBaySearchDTO();
        if (mayBayBLL.search(mayBaySearchDTO).isEmpty()) {
            checkSelectedRow = false;
            tblModel.setRowCount(0);
            JOptionPane.showMessageDialog(this, "Không tìm thấy kết quả phù hợp.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            checkSelectedRow = false;
            fillTable();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refreshInputSearch();
        checkSelectedRow = false;
        fillTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        refreshInputSearch();
        ThemMayBay_Dialog dialog = new ThemMayBay_Dialog(new java.awt.Frame(), true, this);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                dialog.closeDialog(e);
            }
        });
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        refreshInputSearch();
        if (!checkSelectedRow) {
            JOptionPane.showMessageDialog(null, "Vui lòng click vào dòng máy bay muốn chỉnh sửa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int id = Integer.parseInt(idMayBay.getText());
        MayBayDTO mayBayDTO = mayBayBLL.findByid(id);
        if (mayBayDTO == null) {
            JOptionPane.showMessageDialog(null, "Không tìm thấy máy bay trong hệ thống", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            fillTable();
            checkSelectedRow = false;
            return;
        }
        new MayBay_Update(this);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        refreshInputSearch();
        if (!checkSelectedRow) {
            JOptionPane.showMessageDialog(null, "Vui lòng click vào dòng máy bay muốn xóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int id = Integer.parseInt(idMayBay.getText());
        MayBayDTO mayBayDTO = mayBayBLL.findByid(id);
        if (mayBayDTO == null) {
            JOptionPane.showMessageDialog(null, "Không tìm thấy khách hàng trong hệ thống", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            fillTable();
            checkSelectedRow = false;
            return;
        }

        int choice = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa máy bay "
                + mayBayDTO.getTen(), "Xác nhận xóa máy bay", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_NO_OPTION) {
            if (mayBayBLL.delete(mayBayDTO)) {
                fillTable();
                JOptionPane.showMessageDialog(null, "         Xóa thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Xóa thất bại do máy bay vẫn còn nằm bên chuyến bay", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            checkSelectedRow = false;
            fillTable();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tableMayBayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMayBayMouseClicked
        int selectRow = tableMayBay.getSelectedRow();
        if (selectRow >= 0) {
            String id = String.valueOf(tableMayBay.getValueAt(selectRow, 0));
            idMayBay.setText(id);
            checkSelectedRow = true;
        }
    }//GEN-LAST:event_tableMayBayMouseClicked

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        refreshInputSearch();
        if (!checkSelectedRow) {
            JOptionPane.showMessageDialog(null, "Vui lòng click vào dòng máy bay muốn xem chi tiết", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int id = Integer.parseInt(idMayBay.getText());
        MayBayDTO mayBayDTO = mayBayBLL.findByid(id);
        if (mayBayDTO == null) {
            JOptionPane.showMessageDialog(null, "Không tìm thấy máy bay trong hệ thống", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            fillTable();
            return;
        }
        MayBay_Detail_Dialog dialog = new MayBay_Detail_Dialog(new java.awt.Frame(), true, this);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                dialog.closeDialog(e);
            }
        });
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnDetailActionPerformed

    private void xuatExecelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xuatExecelActionPerformed
        Download_Dialog dl = new Download_Dialog(null, true);
        int rs = dl.getpath().showSaveDialog(null);
        Workbook wb = new XSSFWorkbook();

        Sheet sheet = wb.createSheet("MayBay");
        Row row = sheet.createRow(0);

        Cell cell = row.createCell(0);
        cell.setCellValue("Mã máy bay");

        cell = row.createCell(1);
        cell.setCellValue("Tên máy bay");

        cell = row.createCell(2);
        cell.setCellValue("Số ghế thương gia");

        cell = row.createCell(3);
        cell.setCellValue("Số ghế phổ thông");

        cell = row.createCell(4);
        cell.setCellValue("Tình trạng");


        MayBaySearchDTO mayBaySearchDTO = initMayBaySearchDTO();
        int i = 0;
        for (MayBayDTO mayBayDTO : mayBayBLL.search(mayBaySearchDTO)) {
            i++;
            row = sheet.createRow(0 + i);
            cell = row.createCell(0);
            cell.setCellValue(String.valueOf(mayBayDTO.getId()));

            cell = row.createCell(1);
            cell.setCellValue(mayBayDTO.getTen());

            cell = row.createCell(2);
            cell.setCellValue(String.valueOf(mayBayDTO.getSoGheH1()));

            cell = row.createCell(3);
            cell.setCellValue(String.valueOf(mayBayDTO.getSoGheH2()));

            cell = row.createCell(4);
            cell.setCellValue(mayBayDTO.isStatus() ? "Khả dụng" : "Không khả dụng");
        }

        if (rs == JFileChooser.APPROVE_OPTION) {
            File f = dl.getpath().getSelectedFile();
            try {
                FileOutputStream fis = new FileOutputStream(f + ".xlsx");
                wb.write(fis);
                fis.close();
                JOptionPane.showMessageDialog(null, "Xuất file thành công !");
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_xuatExecelActionPerformed

    private void nhapExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapExcelActionPerformed
        try {
            FileInputStream file = new FileInputStream("D:\\MayBay.xlsx");
            XSSFWorkbook workbook = new XSSFWorkbook(file);
            XSSFSheet sheet = workbook.getSheetAt(0);
            Iterator<Row> rowIterator = sheet.iterator();
            List<MayBayDTO> mayBayDTOList = new ArrayList<>();
            while (rowIterator.hasNext()) {
                Row row = rowIterator.next();
                if (row.getRowNum() == 0) {
                    continue;
                }
                MayBayDTO mayBayDTO = new MayBayDTO();
                Iterator<Cell> cellIterator = row.cellIterator();
                while (cellIterator.hasNext()) {
                    Cell cell = cellIterator.next();
                    int columnIndex = cell.getColumnIndex();
                    switch (columnIndex) {
                        case 0:
                            mayBayDTO.setId(Integer.parseInt(cell.getStringCellValue()));
                            break;
                        case 1:
                            mayBayDTO.setTen(cell.getStringCellValue());
                            break;
                        case 2:
                            mayBayDTO.setSoGheH1(Integer.parseInt(cell.getStringCellValue()));
                            break;
                        case 3:
                            mayBayDTO.setSoGheH2(Integer.parseInt(cell.getStringCellValue()));
                            break;
                        case 4:
                            mayBayDTO.setStatus(cell.getStringCellValue().equals("Khả dụng") ? true : false);
                            break;
                        default:
                            break;
                    }
                }
                if (mayBayBLL.findByid(mayBayDTO.getId()) == null) {
                    mayBayDTOList.add(mayBayDTO);
                } else {
                    System.out.println("Mã máy bay " + mayBayDTO.getId() + " đã tồn tại trong cơ sở dữ liệu. Bỏ qua dòng này.");
                }
            }
            for (MayBayDTO mayBayDTO : mayBayDTOList) {
                mayBayBLL.create(mayBayDTO);
            }
            workbook.close();
            file.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_nhapExcelActionPerformed

    public JTextField getIdMayBay() {
        return idMayBay;
    }

    public boolean isCheckSelectedRow() {
        return checkSelectedRow;
    }

    public void setCheckSelectedRow(boolean checkSelectedRow) {
        this.checkSelectedRow = checkSelectedRow;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField idMayBay;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JButton nhapExcel;
    private javax.swing.JTextField soGhePhoThongDen;
    private javax.swing.JTextField soGhePhoThongTu;
    private javax.swing.JTextField soGheThuongGiaDen;
    private javax.swing.JTextField soGheThuongGiaTu;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTable tableMayBay;
    private javax.swing.JButton xuatExecel;
    // End of variables declaration//GEN-END:variables
}
